# PR 우선순위 추천 규칙 설정
# 하드코딩된 우선순위 로직을 설정으로 분리하여 유연성 확보

priority_rules:
  # 첫 번째 우선순위: 보안/인증 관련 변경 (가장 높은 우선순위)
  security:
    priority_level: "CRITICAL"
    keywords:
      - "auth"
      - "security" 
      - "jwt"
      - "password"
      - "token"
      - "login"
    descriptions:
      jwt: "JWT 토큰"
      auth: "인증"
      security: "보안 설정"
      password: "로그인/토큰"
      token: "로그인/토큰"
      login: "로그인/토큰"
    reason_template: "{files} 등의 보안 관련 파일이 수정되었습니다. {security_desc} 검증 로직과 권한 체크, 보안 취약점이 없는지 확인해주세요."
    title_template: "{security_desc} 로직 수정"

  # 두 번째 우선순위: 데이터베이스/API 변경
  database:
    priority_level: "HIGH"
    keywords:
      - "model"
      - "entity"
      - "migration"
      - "schema"
      - "database"
      - "repository"
    descriptions:
      entity: "엔티티/모델"
      model: "엔티티/모델"
      migration: "마이그레이션"
      repository: "레포지토리"
      schema: "스키마"
      database: "데이터베이스"
    reason_template: "{files} 등의 데이터베이스 관련 파일이 수정되었습니다. 스키마 변경사항, 데이터 무결성, 마이그레이션 스크립트를 확인해주세요."
    title_template: "데이터베이스 {db_desc} 변경"

  api:
    priority_level: "HIGH"
    keywords:
      - "controller"
      - "api"
      - "endpoint"
      - "route"
      - "handler"
    descriptions:
      controller: "컨트롤러"
      api: "API"
      endpoint: "엔드포인트"
      route: "엔드포인트"
      handler: "핸들러"
    reason_template: "{files} 등의 API 관련 파일이 수정되었습니다. 요청/응답 스펙 변경, 기존 클라이언트 호환성, 에러 처리를 확인해주세요."
    title_template: "{api_desc} 인터페이스 변경"

  # 세 번째 우선순위: 테스트 및 기타 변경
  test:
    priority_level: "MEDIUM"
    keywords:
      - "test"
    descriptions:
      test: "테스트"
    reason_template: "{files} 등의 테스트 파일이 수정되었습니다. 테스트 시나리오 적절성, 커버리지, 테스트 코드 품질을 확인해주세요."
    title_template: "테스트 코드 추가/수정"

# 변경 규모별 우선순위 기준
change_scale_rules:
  large_scale:
    condition:
      total_changes: 500  # 500라인 이상
      file_count: 15      # 15개 파일 이상
    priority_level: "HIGH"
    title: "대규모 기능 구현"
    reason_template: "{files} 등 총 {file_count}개 파일에 {total_changes}라인이 변경되었습니다. 전체적인 아키텍처 영향도와 기능 간 연관성을 확인해주세요."
    
  small_scale:
    condition:
      total_changes: 50   # 50라인 미만
      file_count: 3       # 3개 파일 이하
    priority_level: "LOW"
    title: "소규모 수정사항"
    reason_template: "{files} 파일에 {total_changes}라인의 소규모 변경이 있습니다. 기본적인 코드 리뷰 후 안전하게 진행해주세요."

# 기본 폴백 규칙들
fallback_rules:
  general_feature:
    priority_level: "MEDIUM"
    title: "일반 기능 변경"
    reason_template: "{files} 등에서 기능이 수정되었습니다. 비즈니스 로직이 올바르게 구현되었는지와 예외 처리를 확인해주세요."
    
  internal_logic:
    priority_level: "MEDIUM"
    title: "내부 로직 구현"
    reason_template: "내부 비즈니스 로직이 구현되었습니다. 코드 품질, 성능, 가독성 측면에서 검토해주세요."
    
  code_quality:
    priority_level: "MEDIUM"
    title: "코드 품질 검토"
    reason_template: "여러 파일에 걸친 변경사항이 있습니다. 코딩 컨벤션 준수, 성능 이슈, 유지보수성을 중점적으로 확인해주세요."

# 에러 상황에서 사용할 기본값들
error_fallback:
  - title: "분석 오류로 인한 기본 설정"
    priority_level: "MEDIUM"
    reason: "우선순위 분석 중 오류가 발생하여 기본 중간 우선순위로 설정했습니다."
  - title: "수동 검토 필요"
    priority_level: "MEDIUM"
    reason: "자동 분석이 실패하여 수동으로 우선순위를 결정해주세요."
  - title: "안전한 기본값 적용"
    priority_level: "MEDIUM"
    reason: "시스템 오류로 인해 안전한 기본값을 적용했습니다."