# -----------------------------------------------------------
# 공통 설정 (모든 프로필에 적용)
# -----------------------------------------------------------
spring:
  application:
    name: ottereview

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none   # local 개발 시 update 등으로 바꿀 수 있음
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false

  sql:
    init:
      mode: never  # 필요 시 always로

github:
  app:
    app-id: ${GITHUB_APP_ID:}
    private-key-path: ${GITHUB_APP_PRIVATE_KEY_PATH:classpath:github-api-privatekey.der}
  oauth:
    client-id: ${GITHUB_APP_CLIENT_ID:}
    client-secret: ${GITHUB_APP_CLIENT_SECRET:}

logging:
  level:
    root: INFO
    com.ssafy.ottereview: DEBUG

---
# -----------------------------------------------------------
# local 프로필 (개발용)
# docker-compose 환경 변수와 주로 함께 사용
# -----------------------------------------------------------
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중 스키마 자동 반영 (운영에서는 사용 X)
    show-sql: true

  sql:
    init:
      mode: never
