version: '3.8'

services:
  # FastAPI + Chroma 서비스
  ai-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENV=development
      - CHROMA_DB_PATH=/app/chroma_db
    volumes:
      - ./models:/app/models              # AI 모델 캐시
      - chroma_data:/app/chroma_db        # ChromaDB 영구 저장 (Named Volume)
    restart: unless-stopped
    networks:
      - ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  ai-network:
    driver: bridge

volumes:
  chroma_data:
    driver: local