version: '3.8'

services:
  # FastAPI + Pinecone 서비스
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ottereview-ai:latest
    container_name: ottereview-ai
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    volumes:
      - ./models:/app/models              # AI 모델 캐시
    restart: always
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  springboot-mysql-net:
    driver: bridge
    external: true